spring:

  datasource:
    url: jdbc:mysql://localhost:3306/userratings?useSSL=false
    username: root

  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  mvc:
    view:
      prefix: WEB-INF/
      suffix: .jsp

logging.level:
  root: INFO

ratings.url: http://localhost:8083/ratingsdata

movies.url: http://localhost:8082/movies
